Add template and basic behaviour
DanielMuckelbauer/RockPaperScissors-Frontend pull request #20
Opened 2022-10-03 09:22 UTC by Hakem22

The purpose of this PR is just to add some template and basic behavior so the flow of the application is a bit understandable.

1- The CSS class name is a pain in the ass, I am ready for any suggestions so just shoot me.
2- The unit test will be added in a follow-up commit (maybe)
3- This is not the final UI, I added task #18 where we can explore UI framework and decide on one.

<img width="1594" alt="image" src="https://user-images.githubusercontent.com/17585880/193542919-2d3ce426-24fa-4ebd-b20c-0c934463cc0a.png">
<img width="1532" alt="image" src="https://user-images.githubusercontent.com/17585880/193543008-4119e49b-5b20-4c3a-b321-7931a8b05cf3.png">

2022-10-03 19:19 UTC, DanielMuckelbauer requested changes

2022-10-03 19:19 UTC, DanielMuckelbauer commented on src/room-creation/RoomCreationModal.svelte
> +        const roomCreationRequest = <RoomCreationRequest>roomForm
```suggestion
const roomCreationRequest = roomForm as RoomCreationRequest;
```

2022-10-03 19:19 UTC, DanielMuckelbauer commented on src/room-creation/RoomCreationModal.svelte
> +        const roomCreationRequest = <RoomCreationRequest>roomForm
`;` missing? if so, please add the lint rule for that :D

2022-10-03 19:19 UTC, DanielMuckelbauer commented on src/room-creation/RoomCreationModal.svelte
> +        open = false;
I preferred my cool way of calling the method instead, but whatevs imenE. I hope in the future the method will do more than flip the flag, and then I will laugh loudly because we will change it here!

2022-10-03 19:19 UTC, DanielMuckelbauer commented on src/room-creation/RoomCreationModal.svelte
> +                <label>Nome</label>
```suggestion
<label>Name</label>
```

2022-10-03 19:19 UTC, DanielMuckelbauer commented on src/room-creation/RoomCreationModal.svelte
> +                    <RadioButton bind:group={roomForm.winnerOrLooser} value={GameType.Looser}>Looser</RadioButton>
as far as I know, loser is written with one `o` :)

2022-10-03 19:19 UTC, DanielMuckelbauer commented on src/room-creation/RoomCreationModal.svelte
> +    li > label {
I would prefer if we stick to `rem` as unit for these things, unless there is some strange styling reason I don't know about that contradicts that in this case

2022-10-03 19:19 UTC, DanielMuckelbauer commented on package.json
>      "svelte-jester": "^2.3.2",
I don't see how this is used, could you explain please?

2022-10-03 19:19 UTC, DanielMuckelbauer commented on src/room-starting/Room.svelte
> +    .button-wrapper{
whitespace, maybe add to linter :)

2022-10-03 19:19 UTC, DanielMuckelbauer commented on src/room-starting/Room.svelte
> +        padding: 2px;
Same here with the `px`. But maybe leave it for now and create a task?
I think what really should be is setting the font size of the root html to 10px or so, and then use `rem` everywhere and it will depend on it.

2022-10-03 19:19 UTC, DanielMuckelbauer commented on src/room-starting/Room.svelte
> +    export let location;
Is this used?

2022-10-03 19:19 UTC, DanielMuckelbauer commented on src/room-starting/Room.svelte
> +        copyClipBoard.$destroy();
I wonder, can't we just set the clipboard using js on buttonclick somehow like [this](https://stackoverflow.com/questions/400212/how-do-i-copy-to-the-clipboard-in-javascript)?
It seems clunky to create and destroy a component for that

2022-10-03 19:19 UTC, DanielMuckelbauer commented on src/room-starting/Room.svelte
> +    }
Can't we just set the clipboard using js api like here maybe?
https://stackoverflow.com/questions/400212/how-do-i-copy-to-the-clipboard-in-javascript

2022-10-03 19:19 UTC, DanielMuckelbauer commented on src/App.svelte
> +	<p>© 2022 rspgame</p>
love it

2022-10-03 19:19 UTC, DanielMuckelbauer commented on src/App.svelte
> +		font-size: 2em;
maybe also `rem` :)

2022-10-06 19:34 UTC, Hakem22 commented on src/room-starting/Room.svelte
> +        padding: 2px;
#22

2022-10-06 19:35 UTC, Hakem22 commented on src/room-creation/RoomCreationModal.svelte
> +    import {Button, ContentDialog, RadioButton, TextBox} from "fluent-svelte";
Done!

2022-10-06 19:42 UTC, Hakem22 commented on src/room-creation/RoomCreationModal.svelte
> +        const roomCreationRequest = <RoomCreationRequest>roomForm
#23

2022-10-06 19:44 UTC, Hakem22 commented on src/room-creation/RoomCreationModal.svelte
> +        open = false;
IT IS MORE THAN FLIPPING THE FLAG, it navigates you in a very smooth delightful way!
Noted though :)

2022-10-06 19:48 UTC, Hakem22 commented on src/room-starting/Room.svelte
> +    .button-wrapper{
#23

2022-10-06 19:49 UTC, Hakem22 commented on src/App.svelte
> +		font-size: 2em;
fixed

2022-10-06 19:52 UTC, Hakem22 commented on src/room-creation/RoomCreationModal.svelte
> +                    <RadioButton bind:group={roomForm.winnerOrLooser} value={GameType.Looser}>Looser</RadioButton>
<img width="299" alt="image" src="https://user-images.githubusercontent.com/17585880/194405974-8b792ceb-68df-4744-9741-00943b61f36a.png">

2022-10-06 19:55 UTC, Hakem22 commented on src/room-creation/RoomCreationModal.svelte
> +        const roomCreationRequest = <RoomCreationRequest>roomForm
Fixed somehow, I don't even know how!!!

2022-10-06 20:24 UTC, Hakem22 commented on src/room-starting/Room.svelte
> +    export let location;
I wanted to get rid of the warning :(
<img width="725" alt="image" src="https://user-images.githubusercontent.com/17585880/194410597-fd562f10-28cf-41ca-8ea7-d23db86cee14.png">

[The issue is quite common](https://github.com/EmilTholin/svelte-routing/issues/122), we need to have a look if we can use another dependency :(

2022-10-06 20:27 UTC, Hakem22 commented on package.json
>      "svelte-jester": "^2.3.2",
Well, yeah when I was trying things :)

2022-10-07 07:51 UTC, Hakem22 commented on src/room-creation/RoomCreationModal.svelte
> +    li > label {
SO, I see you pushing too much for `rem` :), I know the benefit of it. But you know the modern browsers changed their default scaling by zooming on everything. They take care of making reference pixels larger or smaller. so I don't see the relevance of using `rem` instead of `px,` since it is a web app, not mobile or desktop, but I am fine using it.

Now, regarding this comment, I do agree that we should stick to one unit, I change it to `rem`, but I think if we want to go down that way, we use `em` because it depends on the modal and not the root HTML

2022-10-07 08:04 UTC, Hakem22 commented on src/room-starting/Room.svelte
> +        copyClipBoard.$destroy();
hmm, I wanted also to do like angular way here https://stackoverflow.com/questions/49102724/angular-5-copy-to-clipboard where you just add that method.
But then I choose to follow the svelte version https://svelte.dev/repl/3194502389af4e22991f8bb0c61d65cf?version=3.16.5
Hmm, I am really opinionated about this, I can give it another try to do it in a less "clunky" way as you have called it.
I am also fine of create a separate task for it, so this pr won't be a blocker anymore. WHATEVER YOU PREFER

2022-10-07 08:26 UTC, DanielMuckelbauer commented on src/room-starting/Room.svelte
> +        copyClipBoard.$destroy();
You are opinionated or not? I don't think the svelte way you posted is something official, everybody can save their own snippets there no? There is even some chinese comment :)

2022-10-07 13:47 UTC, Hakem22 commented on src/room-starting/Room.svelte
> +        copyClipBoard.$destroy();
Updated, happy that you spotted this out

2022-10-08 15:40 UTC, Hakem22 commented on src/room-starting/Room.svelte
> +        padding: 2px;
Done

2022-10-08 16:48 UTC, DanielMuckelbauer approved these changes

2022-10-08 16:50 UTC, merged